name: Terraform Plan and Apply
on: 
  workflow_dispatch:
  #push:
    #branches:
      #- main 
      #- test - This is to shows that multiple branches can be targeted for a spwcific triger
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read
  issues: write

concurrency: my devsecops #This will ensure that only a single workflow is run at a time


jobs:
  kics:
    name: 'Run KICS scan'
    uses: ./.github/workflows/terraform_kics.yml
    with:
      ENABLE_COMMENTS: true
      WORKING_DIRECTORY:  'infrastructure/region/iam_group'
  
  run_plan_in_prod_environment:
    name:  terraform init, validate, plan
    needs:  [kics]
    uses:  ./.github/workflows/reuseable_plan_actions.yml
    with:
      #ENVIRONMENT_NAME: 'prod'
      TERRAFORM_WORKING_DIR: ./applied/prod
      TERRAFORM_VERSION: '1.7.2'
      TERRAGRUNT_VERSION: '0.56.0'
      AWS_REGION: 'us-east-1'
    secrets: inherit

  run_apply_in_prod_environment:
    name: terraform init, apply
    needs: [run_plan_in_prod_environment]
    uses: ./.github/workflows/reuseable_apply_actions.yml
    with:
      #ENVIRONMENT_NAME: 'prod'
      TERRAFORM_WORKING_DIR: ./applied/prod
      TERRAFORM_VERSION: '1.7.2'
      TERRAGRUNT_VERSION: '0.56.0'
      AWS_REGION: 'us-east-1'
    secrets: inherit
  
  run_plan_in_dev_environment:
    name:  terraform init, validate, plan
    uses:  ./.github/workflows/reuseable_plan_actions.yml
    with:
      #ENVIRONMENT_NAME: 'dev'
      TERRAFORM_WORKING_DIR: ./applied/dev
      TERRAFORM_VERSION: '1.7.2'
      TERRAGRUNT_VERSION: '0.58.0'
      AWS_REGION: 'us-east-1'
    secrets: inherit

  run_apply_in_dev_environment:
    name: terraform init, apply
    needs: [run_plan_in_prod_environment]
    uses: ./.github/workflows/reuseable_apply_actions.yml
    with:
      #ENVIRONMENT_NAME: 'prod'
      TERRAFORM_WORKING_DIR: ./applied/dev
      TERRAFORM_VERSION: '1.7.2'
      TERRAGRUNT_VERSION: '0.58.0'
      AWS_REGION: 'us-east-1'
    secrets: inherit

  

  
